Yubico/yubico-piv-tool

tool/yubico-piv-tool.c

when unblock-pin action is called without -P and -N parameter, the wrong
error is returned, saying that -P should be a pin, whereas in this
action it is a puk.
**WRONG**
$ yubico-piv-tool -a unblock-pin                      
The unblock-pin action needs a pin (-P) and a new-pin (-N).
**CORRECT**
$ yubico-piv-tool -a unblock-pin                      
The unblock-pin action needs a puk (-P) and a new-pin (-N).

Fixed error when parameters in unblock-pin

---

tool/util.c
tool/util.h
tool/yubico-piv-tool.c

Do not force a user to specify the PIN/PUK/mgmt-key on the command line.
Instead, query the user to supply them through stdin when required for
the requested operation.  This is both more user friendly and more
secure, since the secrets do not end up in the shell history and/or
visible to shoulder-surfers on the terminal.

Query for PIN/PUK/mgmt-key if not supplied on command line

---

doc/SSH_with_PIV_and_PKCS11.adoc

While reading the  docs for the first time, I had a WTF moment when it started talking about x.509 cerificates. Later I found our more info from here http://blog.josefsson.org/2015/06/16/ssh-host-certificates-with-yubikey-neo/
Also, the private key export step is missing the -e argument 
I have tried to update the docs to include all this info

Update Neo SSH integration guide.

---

mac.mk

Let's say I want to use YKCS11 with ssh. Because of System Integrity Protection, I've installed yubico-piv-tool in /opt/yubico-piv-tool/, so libykcs11.dylib is in /opt/yubico-piv-tool/lib/.
When I run ssh, I get something like this:
$ ssh -I /opt/yubico-piv-tool/lib/libykcs11.dylib root@example.com
dlopen /opt/yubico-piv-tool/lib/libykcs11.dylib failed: dlopen(/opt/yubico-piv-tool/lib/libykcs11.dylib, 2): Library not loaded: @executable_path/../lib/libykpiv.1.dylib
Referenced from: /opt/yubico-piv-tool/lib/libykcs11.1.dylib
Reason: unsafe use of @executable_path in /opt/yubico-piv-tool/lib/libykcs11.dylib with restricted binary
Permission denied (publickey,keyboard-interactive).
I think this specific error message may actually be caused by System Integrity Protection, but even without …

Use @loader_path rather than @executable_path for OS X dylib paths

---

ykcs11/token_vendors.c

C_Login fails with CKR_PIN_INCORRECT when pin and pinLen are valid but pin is not null terminated

Fixed bug #39

---

tool/cmdline.ggo
tool/yubico-piv-tool.c

Adds `--valid-days` and `--serial` parameters that configure the expiration (`notAfter`) and serial of self-signed certificates generated using the `selfsign-certificate` action.
```
$ yubico-piv-tool -a verify-pin -P 123456 -a selfsign-certificate -s 9a -S "/CN=Yubikey Token/" -i public.pem -o cert.pem --valid-days 10 --serial 123456789
Successfully verified PIN.
Successfully generated a new self signed certificate.
$ openssl x509 -noout -text -in cert.pem
Certificate:
Data:
Version: 3 (0x2)
Serial Number: 123456789 (0x75bcd15)
Signature Algorithm: ecdsa-with-SHA256
Issuer: CN=Yubikey Token
Validity
Not Before: Feb 10 23:44:08 2016 GMT
Not After : Feb 20 23:44:08 2016 GMT
Subject: CN=Yubikey Token
Subject Public Key Info:
Public Key Algorithm: id-ecPublicKey
EC Public Key:
pub: …
```

Add options for configuring self-signed certs.

---

lib/ykpiv.h
tool/yubico-piv-tool.c
ykcs11/token_vendors.c

Replace the magic constant 0x80 when sending a packet to the key

Add YKPIV_ALGO_TAG

---

lib/ykpiv.c
lib/ykpiv.h
tool/yubico-piv-tool.c

Most come from NIST special publication 800-73-4, section 5.6,
except one which I assume to be a custom one for yubikey.

Replace magic number for status word by constants

---

doc/SSH_with_PIV_and_PKCS11.adoc

Works fine on clean installs of sierra - just needs opensc from homebrew

Update documentation on ssh-agent on macos

---

doc/SSH_with_PIV_and_PKCS11.adoc

I kept some notes for things which I had to figure out to get my system configured and write some private documentation:
* Explain how to use a non-default management key
* Explain why `-A RSA4096` isn't an option
* Remove `-P 123456` from the self-sign step to avoid encouraging people to leak their PIN into shell history files; `yubico-piv-tool` will securely prompt for the PIN by default
* Avoid forcing line-wrapping in shell examples, which complicated shell editing
* Show Mac Homebrew users how to reliably determine the opensc lib path

Improve SSH with PIV and PKCS11 instructions for newbies

---

ykcs11/mechanisms.c
ykcs11/openssl_types.h
ykcs11/openssl_utils.c
ykcs11/openssl_utils.h
ykcs11/ykcs11.c
ykcs11/ykcs11.h

fixes #25 #111
The code on master was slightly wrong:
- it stored only the raw modulus in `op_info.op.sign.key` (see https://github.com/Yubico/yubico-piv-tool/blob/8e91c8ea2f6ad670b15cd34dda336a1af1a709c3/ykcs11/ykcs11.c#L1755-L1769) -- where the call to `malloc` used `key_len`, which is the bit length of the RSA key
- this (overly long) buffer was passed to OpenSSL `d2i_RSAPublicKey` (via https://github.com/Yubico/yubico-piv-tool/blob/8e91c8ea2f6ad670b15cd34dda336a1af1a709c3/ykcs11/mechanisms.c#L286 and https://github.com/Yubico/yubico-piv-tool/blob/8e91c8ea2f6ad670b15cd34dda336a1af1a709c3/ykcs11/openssl_utils.c#L470), which failed since `d2i_` expects a full key (algorithmIdentifier, modulus, exponent) DER encoded ASN.1 buffer.
- The `malloc()`ed buffer was never `free()`d.
Now, instead …

fix PSS signing support

---

lib/ykpiv.c
tool/Makefile.am
tool/openssl-compat.c
tool/openssl-compat.h
tool/util.c
tool/yubico-piv-tool.c
ykcs11/openssl_utils.c
ykcs11/tests/ykcs11_tests.c

Update 2017-11-14: Resolves  #104. Tested with latest Yubikey 4 with hardware tests, provisioning new key and selfsigning certificates.

OopenSSL 1.1.0 compatibility

---

tool/openssl-compat.c
tool/openssl-compat.h
tool/yubico-piv-tool.c
ykcs11/openssl_utils.c
ykcs11/tests/ykcs11_tests.c

Previously, compiling against LibreSSL worked seamlessly due to being API compatible with OpenSSL 1.0.1. This was broken when OpenSSL 1.1.0 support was added due to the OpenSSL version check conflicting with the LibreSSL versioning scheme.
This PR mitigates the problem by checking the LIBRESSL_VERSION_NUMBER macro where applicable.

Added checks to allow building against LibreSSL

---

tool/util.c
tool/yubico-piv-tool.c
ykcs11/openssl_types.h
ykcs11/openssl_utils.c

OpenSSL 1.1.0 can be compiled in a variety of compatibility modes. On my machine, OpenSSL 1.1.0 has all compatibility APIs disabled by default.
This PR thus removes/replaces all calls to deprecated APIs when compiling against OpenSSL 1.1.0, and also adds some required headers.
Please review and feel free to comment so I can adjust things. :)

Improve compatibility with OpenSSL 1.1.0

---

lib/tests/api.c
lib/util.c
tool/util.c

While trying to build the latest version of `yubico-piv-tool` for EPEL7, I encountered several issues, mostly, the RHEL/CentOS 7 has older version of `check` (`check-0.9.9-5.el7.x86_64`), which does not provide the `ck_assert_ptr_eq`, but it can be simply rewritten to `ck_assert`. Secondly, there showed up some warnings, mostly in context of not running the HW tests at build time.
With these patches, I am able to build the package on both current Fedora and RHEL7 successfully (I did not test the HW_TEST though -- I don't have spare Yubikey at this moment).

Compiler warnings and compatibility with older check versions

---

lib/ykpiv.c

sadly strcasestr is a GNU/BSD extension, not part of posix so we have to
do our own thing here or do different things on different platforms.

lib: make the reader comparison case-insensitive

---

configure.ac
lib/internal.c
lib/internal.h
lib/util.c
lib/ykpiv.c
lib/ykpiv.h
lib/ykpiv.map
tool/yubico-piv-tool.c

lib: promote get_serial to base API
lib: add ykpiv_get_serial to external API
tool: add serial number/version to status command
build: fix msvc build of case insensitive-reader (missing strncasecmp and cast warnings)
lib: consolidate neo/yk4 + yk5 serial number routines
lib: fix GCC 8 compilier warnings
lib: reimplement deauthenticate to select mgmt aid
build: disable -Waggregate-return
lib: fix warning differences between gcc and msvc
lib: add option to disable implicit card transactions
lib: remove application reselect prior to crypt operations
build: fix msvc warnings wrt length checking logic fixes
lib: fix error condition logic in untransacted internal functions
lib: create internal transactionless ykpiv_transfer_data

libykpiv/piv-tool 1.6.3

---

lib/internal.c
lib/ykpiv.c
ykcs11/ykcs11.c

lib: warn, but don't fail on error reading serial number or version
lib: fix Windows build with OpenSSL 1.1.1
ykcs11: fix size_t/unsigned long type mismatch on Windows x64

Serial number + Windows build fixes

---

ykcs11/mechanisms.c

Adding a `CKA_LABEL` attribute when calling `C_GenerateKeyPair` will cause a `CKR_ATTRIBUTE_TYPE_INVALID` error as it is falls through to the default case.
It appears that the label value defaults to e.g. `Public key for PIV Authentication` so I assumed this error is not necessary.

Ignore CKA_LABEL on calls to check_{pub/pvt}key_template

---

lib/ykpiv.c
ykcs11/ykcs11.c

valgrind --track-origins=true says:
==13529== Conditional jump or move depends on uninitialised value(s)
==13529==    at 0x4AF92D1: PK11_MakeString (pk11slot.c:1073)
==13529==    by 0x4AFA5AA: PK11_InitSlot (pk11slot.c:1456)
==13529==    by 0x4AE315E: secmod_LoadPKCS11Module (pk11load.c:563)
==13529==    by 0x4AEF68C: SECMOD_LoadModule (pk11pars.c:1838)
==13529==    by 0x4AEF7C7: SECMOD_LoadModule (pk11pars.c:1874)
==13529==    by 0x4ABCB6A: nss_InitModules (nssinit.c:464)
==13529==    by 0x4ABCB6A: nss_Init (nssinit.c:689)
==13529==    by 0x4ABD17C: NSS_Init (nssinit.c:824)
==13529==    by 0x4059C0: main (pesign.c:354)
==13529==  Uninitialised value was created by a stack allocation
==13529==    at 0x484D175: C_Initialize (in /usr/lib64/libykcs11.so.1.5.0)
This is the result of a …

Initialize C_Initialize's reader list to NULs.

---

doc/YKCS11_release_notes.adoc

This is deprecated and no longer needed.

Remove note about ifd-yubico.

---

tool/yubico-piv-tool.c

Key needs to be 48 but also only hexidecimal is supported. This is not very clear in the error nor in documentation at https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.html

Clarifying mgmt key error

---

tool/yubico-piv-tool.c

instead of repeating almost word-for-word the diagnostic error from ykcs11 lib (which is show right above this line btw), show something that have *any* meaning to the end user, who likely do not know what a "reader" is.
Before:
```
$ yubico-piv-tool --verbose -a status
error: no usable reader found.
Failed to connect to reader.
```
after
```
$ yubico-piv-tool --verbose -a status
error: no usable reader found.
Failed to connect to yubikey.
Have you tried turning it off and on again
```
The last line is, obviously, helpful but extraneous, mostly to make a point that i am not a contributor here and someone who knows the end users better than i do should write the actual new text.

error message when yubikey must be reinserted.

---

tool/yubico-piv-tool.c

From commit f422a51486, ("Remove old ASN.1 code.", 2015-03-14),
OpenSSL no longer provides M_ASN1_* macro.
In that change, OpenSSL replaced M_ASN1_BIT_STRING_set with
ASN1_STRING_set.
Follow OpenSSL steps to support all rolling-release distro.
Signed-off-by: Doan Tran Cong Danh <congdanhqx@gmail.com>
---
https://github.com/openssl/openssl/commit/f422a51486

yubico-piv-tool: avoid obsolete macro M_ASN1_BIT_STRING_set

---

ykcs11/token.c

Using the OPENSSL_cleanse since it was already used, might make sense to pull in yk_memzero from lib/internal.h instead but that would require some refactoring.

Do not leave potential sensitive materials on the stack

---

lib/ykpiv.h

This PR makes sure the `ykpiv-version.h` header is included with a relative path.
This allows users to include the `ykpiv.h` header through `#include <ykpiv/ykpiv.h>` without adding `/usr/include/ykpiv` to the include path.

Use relative path to include ykpiv-version.h

---

tool/yubico-piv-tool.c

This avoids a potential buffer overflow in fread().
Reported by Ilja van Sprundel, thanks!

tool: check int length before conversion to size_t

---

tool/CMakeLists.txt

It was omitting the man page upon first install, so in order to get the man page added to the installed set of files, one would have to run `cmake`, then run `make`, then run `cmake` again, then run `make install`.
This commit just hinges the installed file declaration on whether we want to generate man pages. If the man page generation fails, it'll still fail the build like before.

Fix omission of man page

---

common/openssl-compat.c
ykcs11/mechanisms.c
ykcs11/pkcs11.h
ykcs11/pkcs11y.h

Aligned to use the same pkcs11.h as yubihsm-shell, which includes the OAEP and PSS parameter definitions, properly aligned. This fixes an issue on Windows.

Using same pkcs11.h as yubihsm-shell

---

ykcs11/openssl_utils.c
ykcs11/tests/ykcs11_tests.c
ykcs11/tests/ykcs11_tests_util.c

and also remove a potential double free in the error path.

Close more minor memory leak

---

CMakeLists.txt

ABI compatibility broke, as the symbol versioning scheme changed, so `SO_VERSION` needs to be increased. 
This presumably happened due to the switch to CMake.
Discovered while packaging v2.1.1 for Debian.

Bump SO_VERSION

---

ykcs11/mechanisms.c
ykcs11/objects.c
ykcs11/tests/ykcs11_tests_util.c

See https://github.com/Yubico/yubico-piv-tool/issues/291

Ignore and return CK_FALSE for CKA_SIGN_RECOVER

---

cmake/help2man.cmake
tool/CMakeLists.txt

`help2man`'s `-n` parameter takes a description of the command,
and is used in generating the `whatis` entry.
Without a description, it defaults to something worse-than-useless:
`manual page for yubico-piv-tool ${version}`.

yubico-piv-tool: Put useful description in manpage

---

ykcs11/objects.c
ykcs11/openssl_utils.c
ykcs11/tests/ykcs11_tests.c

Handle segfault due to no public key being present in certain circumstance, such as importing a key to a slot that had no key when the session was opened. Also fixed a bug in tests causing stack overwrite if running tests with more than one YubiKey attached.

Handle no pubkey

---

ykcs11/mechanisms.c
ykcs11/objects.c

Make both `CKA_SENSITIVE` and `CKA_EXTRACTABLE` settable, but also enforce that they are always respectively `CK_TRUE` and `CK_FALSE`.

P11 attributes

---

ykcs11/openssl_types.h

OpenSSL 3.x ships an [`openssl/types.h`](https://github.com/openssl/openssl/blob/master/include/openssl/types.h#L10) header that's protected with an `OPENSSL_TYPES_H` include guard macro.  OpenSSL's headers fail to parse when `ykcs11/openssl_types.h` defines this symbol.
Switch the include guard for the file to `YKCS11_OPENSSL_TYPES_H` to prevent this from happening.

Avoid header include guard conflict with OpenSSL 3

---

tool/yubico-piv-tool.c

Call setlocale on startup, possible fix for https://github.com/Yubico/yubico-piv-tool/issues/296

Call setlocale on startup

---

common/util.c
lib/internal.h
lib/ykpiv.c

Requires remembering the reader name. Should also check serial number

Re-establish context if no longer available.

---

CMakeLists.txt
tool/yubico-piv-tool.c
ykcs11/mechanisms.c
ykcs11/openssl_utils.c

The method API has subtle differences in OpenSSL 3 vs 1.1 which required a rewrite, but the new code works for both versions

Compile cleanly with openssl 1.1 & 3

---

ykcs11/tests/ykcs11_tests_util.c

This PR fixes problems found while building on Fedora 36. Build fails with maybe-uninitialized variables and usage of pointer after the `free()` in `ykcs11_tests_util.c`.

Fix usage of pointer after free

---

CMakeLists.txt
lib/internal.c
lib/internal.h
lib/util.c
lib/ykpiv.c
tool/yubico-piv-tool.c
ykcs11/mechanisms.c
ykcs11/openssl_utils.c
ykcs11/token.c
ykcs11/utils.c

Remove as many supressed warnings as feasible, fixing some warnings in code instead

Revisit MSVC warnings supression

---

ykcs11/tests/ykcs11_tests_util.c

gcc 12 includes a new `-Wuse-after-free` warning mode that detects use
of variables after a call to `free()`. While the use of this variable is
not in fact a use-after-free, it is more correct to not reuse the `dec`
variable or explicitly set it to `NULL` after calling `free`.
This is not a security bug.
Signed-Off-By: Dan Fuhry <dan@fuhry.com>

[ykcs11/tests] fix use-after-free warning in gcc 12

---

lib/ykpiv.c
tool/yubico-piv-tool.c
ykcs11/mechanisms.c

Related to https://github.com/Yubico/yubico-piv-tool/issues/412

Better error messages and truncate data for ECC signatures

---

ykcs11/token.c

Fix bug that makes C_SetPIN fail for the MGM key (i.e. logged in as SO)

Fix call to ykpiv_hex_decode

---

doc/Attestation.adoc

@beneichorst provided feedback to the developer program on changes to the PIV attestation documentation on the DYC - The changes reflect the changes provided to us
This request is related to the PR open for the DYC: https://github.com/Yubico/developers.yubico.com/pull/513

Added changes to the PIV documentation based on Ben's feedback

---

tool/yubico-piv-tool.c

The original buffer is not large enough for RSA4096, causing an error:
```
DBG ykpiv.c:1299 (_general_authenticate): Wrong size on output buffer.
RSA decrypt failed!
```

Fix buffer size when testing RSA4096 decipher

---

ykcs11/tests/ykcs11_tests_util.c

on i686, the ULONG is not the same size as size_t and the build fails with errors like:
```
ykcs11/tests/ykcs11_tests_util.c:332:50: error: passing argument 3 of ‘EVP_PKEY_get_raw_private_key’ from incompatible pointer type [-Wincompatible-pointer-types]
332 |   asrt(EVP_PKEY_get_raw_private_key(ed_key, pvt, &pvt_len), 1, "EXTRACTING PRIVATE ED25519 KEY");
|                                                  ^~~~~~~~
|                                                  |
|                                                  CK_ULONG * {aka long unsigned int *}
ykcs11/tests/ykcs11_tests_util.c:64:49: note: in definition of macro ‘asrt’
64 | #define asrt(c, e, m) _asrt(__FILE__, __LINE__, c, e, m);
|                                                 ^
In file included from …
```

tests: Avoid passing incompatible arguments to OpenSSL

---

.github/workflows/codeql-analysis.yml

CodeQL is deprecating v2 on December 5th. This PR merely bumps to v3. The action is verified to run.
background: https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

changing to codeql@v3 as v2 is being deprecated

---

lib/tests/aes.c

While debugging the #522, I changed some of the asserts to report some more useful information. Rather than throwing it away, adding it as a PR. It would help if all the asserts were written in this way instead of as `ck_assert(rv == YKPIV_OK)`.

Report more usable errors from failed asserts

---

ykcs11/openssl_utils.c

[Here](https://github.com/Yubico/yubico-piv-tool/blob/ab53895333cb3fd3147cb67d25d1d1b6c140c765/ykcs11/openssl_utils.c#L74) 
`  if(oaep_md != NULL && oaep_mgf1 != NULL && oaep_label != NULL) {`
a hash for the RSA OAEP encryption is set only if every parameter isn't null.
When oaep_label is null, OpenSSL properly encrypts the message and the encrypted message is properly decrypted by OpenSSL and the token. However, if I am encrypting the message with the token, ykcs11 doesn't set specified mgf1 and md parameters, thus the default SHA1/MGF_SHA1 scheme seems to kick in, and decrypting the message with the same parameters used for encryption fails.
Steps to reproduce:
```shell
dd if=/dev/zero of=zero190.bin bs=1 count=190
echo "Producing effectively SHA1 message, even though asked for SHA256" …
```

Honor hash function set for RSA PKCS1 OAEP encryption
