Yubico/yubico-piv-tool

- ykcs11/utils.c
- ykcs11/ykcs11.c
> Fix bugs windows

- doc/Windows_certificate.adoc
Supply the management key value during generate key if it has ever been modified
> Supplying --key when management key value is longer the default value

- doc/YKCS11_release_notes.adoc
- doc/YubiKey_PIV_introduction.adoc
- lib/version.c
- m4/pkg.m4
- ykcs11/pkcs11.h
- ykcs11/utils.c
Small tidy up.
* Upgrade insecure links
* Fix broken URls
> http->https & fix broken links

- .travis.yml
- Makefile.am
- build-and-test.sh
- configure.ac
- lib/internal.c
- lib/tests/Makefile.am
- lib/tests/api.c
- lib/ykpiv.c
- linux.mk
- mac.mk
- tool/Makefile.am
- tool/openssl-compat.c
- tool/openssl-compat.h
- tool/util.c
- tool/yubico-piv-tool.c
- windows.mk
- ykcs11/openssl_utils.c
- ykcs11/tests/Makefile.am
- ykcs11/tests/ykcs11_tests.c
Extends the work of Jakuje (PR #107).  Both OpenSSL 1.0 and 1.1 verified and passing hardware tests on Mac and Linux.  Both versions built in Travis-CI.
> OpenSSL 1.1 compatibility

- tool/yubico-piv-tool.c
- wrap_public_key() passed the address of the local stack variable
internal_key to RSA_meth_set0_data(), which was used long after
wrap_public_key() had returned. Changed to static.
- The callback functions yk_rsa_meth_sign and yk_ec_meth_sign 'siglen'
parameter has type (unisgned int *), which was cast to (size_t *)
before it was used to write a value in the caller's memory
space. This caused stack corruption on machines where size_t is
bigger than unsigned int.
- The callback function's 'siglen' parameter is output-only, not
in-out. The input value was assumed to contain the maximum size of
the output buffer as input, and a bogus value was compared to the
amount of data received from the token in function
_general_authenticate(). Changed to pass in the values returned by
RSA_size(rsa) …
> Fixed some bugs in the port to Openssl-1.1:

- tool/yubico-piv-tool.c
this adds subjectKeyIdentifier, authorityKeyIdentifier and
basicConstraints (CA:TRUE) for selfsigned certificates to match with
openssl req
> tool: add extensions for selfsigned certificates to match openssl

- tool/yubico-piv-tool.c
previous code was on the naive side
> tool: fix selfsigned extensions

- doc/YubiKey_PIV_introduction.adoc
as per https://github.com/Yubico/developers.yubico.com/issues/87
> doc: rely on /dev/urandom's distribution to generate secrets

- ykcs11/yubico_token.c
Add the ability for ykcs11 to change the management key
> lib: Implemented change pin for the management key

- doc/Actions/attest.adoc
- doc/Actions/delete_certificate.adoc
- doc/Actions/index.adoc
- doc/Actions/key_generation.adoc
- doc/Actions/key_import.adoc
- doc/Actions/read_certificate.adoc
- doc/Actions/read_write_objects.adoc
- doc/Actions/reset.adoc
- doc/Actions/signing.adoc
- doc/Actions/status.adoc
- doc/Actions/test-decryption.adoc
- doc/Actions/test-signature.adoc
- doc/Actions/version.adoc
> Added documentation for command line actions

- .github/workflows/scan.yml
Not failing the build pipeline at the moment so can be merged without consequences
> Adding a static code analysis github workflow

- doc/Attestation.adoc
Add a note to Using Attestation [1] about the certificate problems with
YubiKey 4.3.
[1] https://developers.yubico.com/yubico-piv-tool/Attestation.html
> Note about attestation cert problems in YubiKey 4.3

- .github/workflows/windows_build.yml
- lib/ykpiv.c
- lib/ykpiv.h
- ykcs11/ykcs11.c
This fixes the issue with removed & reinserted YubiKeys while a pkcs11 application is running
> Validate pcsc card handles, and reconnect if needed

- lib/internal.c
- lib/util.c
- lib/ykpiv.c
- tool/yubico-piv-tool.c
- ykcs11/tests/ykcs11_tests.c
Remove unneeded pragmas to suppress warnings
> Remove gcc & clang pragmas

- lib/tests/api.c
Fix rebase bug that made us skip aes mgmt key tests
> Fix faulty fix for api change and data_len bug

- ykcs11/objects.c
- ykcs11/objects.h
- ykcs11/tests/ykcs11_tests.c
- ykcs11/tests/ykcs11_tests_util.c
- ykcs11/tests/ykcs11_tests_util.h
- ykcs11/token.c
- ykcs11/token.h
- ykcs11/ykcs11.c
> Support Touch and PIN policies for imported private keys.

- ykcs11/token.c
- ykcs11/token.h
- ykcs11/ykcs11.c
Simplify C_CreateObject and remove token_import_private_key
> Simplify C_CreateObject

- .github/workflows/linux_build.yml
- .github/workflows/linux_libressl_openssl1.0.yml
- .github/workflows/windows_build.yml
Fixing the tests run on Github Actions
> Githubactions

- doc/Attestation.adoc
Correcting OpenSSL commands to provide for proper validation examples using OpenSSL.
> Attestation procedure corrections

- lib/error.c
- lib/util.c
- lib/ykpiv.c
- lib/ykpiv.h
- tool/yubico-piv-tool.c
- ykcs11/token.c
- ykcs11/ykcs11.c
Improve PCSC and general error handling, printing out reason for failures to stderr
> Improved error handling

- .github/workflows/macos_release.yml
- resources/macos/make_release_binaries.sh
Update scripts for MacOS release
> Githubactions MacOS release

- CMakeLists.txt
- NEWS
- debian/changelog
- lib/util.c
- ykcs11/token.c
Fix minor bug effecting certain architectures on Linux plarforms
> Prepare 2.4.1 release

- README
> Add zlib-devel as dependency in README

- tool/yubico-piv-tool.c
Implement the Ed25519 signature verification in test-signature action.
> Support Ed25519 in test-signature action

- lib/util.c
- lib/ykpiv.c
- lib/ykpiv.h
- ykcs11/token.c
This helps debugging where a certain error code came from
> ykpiv_translate_sw_ex shows where it was called from

- ykcs11/mechanisms.c
Hi! Debian QA tools noticed this typo.
> ykcs11: Fix typo
